"""Change Rooms Table

Revision ID: e214ab389284
Revises: c757f460c3a5
Create Date: 2025-04-06 16:17:29.063223

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e214ab389284'
down_revision: Union[str, None] = 'c757f460c3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('services', sa.JSON(), nullable=True))
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'services')
    # ### end Alembic commands ###
