services:
  db:
    image: postgres:16
    container_name: booking_db
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    container_name: booking_redis
    ports:
      - "6379:6379"

  booking:
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    ports:
      - "9000:8000"
    command: [ "/booking/docker/app.sh" ]

  celery:
    build: .
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    command: ["/booking/docker/celery.sh", "celery"]

  flower:
    build: .
    env_file:
      - .env-non-dev
    depends_on:
      - redis
      - celery
    ports:
      - "5555:5555"
    command: ["/booking/docker/celery.sh", "flower"]
